config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users
  resources :charges
  resources :locations
  resources :stores
  resources :categories
  resources :products
  resources :users
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many :products, dependent: :destroy
  validates :name, presence: true
  validates_uniqueness_of :name
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
    filter_params.each do |key, value|
    @stores = @stores.public_send(key,value) if value.present?
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)
    @store.user_id = current_user.id

    respond_to do |format|
      if @store.save
        current_user.add_role(:owner)
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :location_id)
    end

    def not_authorized
      flash[:notice] = "You are not authorized"
      redirect_to products_path
    end

    def filter_params
      params.slice(:search_term)
    end
  end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :store_name %>
  </div>

  <div class="field">
     <%= form.label :location %>
     <%= form.select :location_id, options_from_collection_for_select(Location.all, :id, :full_address), id: :profile_location_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<div class="container">

<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<button><%= link_to 'Show', @store %> </button>
<button><%= link_to 'Back', stores_path %></button>

</div>

app/views/stores/index.html.erb
<div class="container">

<h1>Stores</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Store Owner</th>
      <th>Store Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.user.profile.full_name if store.user.profile.present? %></td>
        <td><%= store.location.full_address  if store.location.present? %></td>
        <td><%= link_to 'Show', store %></td>
        <% if store.user == current_user || user_signed_in? && current_user.has_role?(:admin)%>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <% else %>
        <td></td>
        <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.store.present? %>
<button><%= link_to 'Edit Your Store', edit_store_path(current_user.store) %></button>
<% else %>
<button><%= link_to 'Create New Store', new_store_path %></button>
<% end %>

</div>

app/views/stores/new.html.erb
<div class="container">

<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

</div>

app/views/stores/show.html.erb
<div class="container">

<h1>
  <%= @store.name %>
</h1>

<% if @store.user.profile.present? %>
<p>
    <strong>Owner:</strong>
    <%= @store.user.profile.full_name %>
</p>
<% end %>
<% if @store.products.present? %>
<h3>Products available</h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Price</th>
      <th>Stock level</th>
      <th>Description</th>
      <th>Category</th>
      <th>Store</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @store.products.each do |product| %>
      <tr>
        <td><%= image_tag product.image_url(:thumb) %></td>
        <td><%= product.name %></td>
        <td>$<%= product.price %></td>
        <td><%= product.stock_level %></td>
        <td><%= product.description %></td>
        <td><%= product.category.name %></td>
        <td><%= product.store.name %></td>
        <td><%= link_to 'Show', product %></td>
        <% if product.store.user == current_user || user_signed_in? && current_user.has_role?(:admin)%>
        <td><%= link_to 'Edit', edit_product_path(product)%></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
    <strong>Location:</strong>
    <%= @store.location.full_address %>
</p>
<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDURAe9ccbX3ImKBQj-6z3-fDJug0aV1lE&q=<%=@store.location.full_address%>}" allowfullscreen>
</iframe><br>
<% else %>
<p>This store doesn't have any products yet.</p>
<% end %>

<button><%= link_to 'Edit', edit_store_path(@store) %></button>
<button><%= link_to 'Back', stores_path %></button>

</div>