config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users
  resources :charges
  resources :locations
  resources :stores
  resources :categories
  resources :products
  resources :users
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
     has_one :profile, dependent: :destroy
     has_one :store, dependent: :destroy

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_notification

  def send_notification
      UserMailer.send_signup_email(self).deliver
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    filter_params.each do |key, value|
    @users = @users.public_send(key,value) if value.present?
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :street_address, :location_id, :phone_number, :bio)
    end

    def filter_params
      params.slice(:search_term)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">

<h1>Editing User</h1>

<%= render 'form', user: @user %>

<button><%= link_to 'Show', @user %></button>
<button><%= link_to 'Back', users_path %></button>

</div>

app/views/users/index.html.erb
<div class="container">

<h1>Users</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Location</th>
      <th colspan="4">Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><div class="image-cropper"><%= image_tag user.profile.image_url(:thumb) if user.profile.present? %></div></td>
        <td><%= user.profile.full_name if user.profile.present? %></td>
        <td><%= user.profile.location.full_address if user.profile.present? %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) if user == current_user || user_signed_in? && current_user.has_role?(:admin) %></td>
        <td><%= link_to 'Delete Account?', user, method: :delete, data: {confirm: 'Are you sure?'} if user == current_user || user_signed_in? && current_user.has_role?(:admin) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'Back to Products', products_path %></button>

</div>

app/views/users/show.html.erb
<div class="container">

<p><%= image_tag @user.profile.image_url(:thumb)%></p>


<p>
  <strong>Name:</strong>
  <%= @user.profile.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.profile.location.full_address %>
</p>

<button><%= link_to 'Edit', edit_user_path(@user) %></button>
<button><%= link_to 'Back', users_path %></button>

</div>