config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users
  resources :charges
  resources :locations
  resources :stores
  resources :categories
  resources :products
  resources :users
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    filter_params.each do |key, value|
    @categories = @categories.public_send(key,value) if value.present?
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
    def filter_params
      params.slice(:search_term)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">

<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<button><%= link_to 'Show', @category %></button>
<button><%= link_to 'Back', categories_path %></button>

</div>

app/views/categories/index.html.erb
<div class="container">

<h1>Categories</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Products</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= 'Products available' if category.products.present? %></td>
        <td><%= link_to 'Show', category if category.products.present? %></td>
        <td><%= link_to 'Edit', edit_category_path(category) if current_user.has_role? :admin %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } if current_user.has_role? :admin %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<button><%= link_to 'Create New Category', new_category_path %></button>

</div>

app/views/categories/new.html.erb
<div class="container">

<h1>New Category</h1>

<%= render 'form', category: @category %>

<button><%= link_to 'Back', categories_path %></button>

</div>

app/views/categories/show.html.erb
<div class="container">

<h1><strong>
  <%= @category.name %>
</strong></h1>

<% if @category.products.present? %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Price</th>
      <th>Stock level</th>
      <th>Description</th>
      <th>Category</th>
      <th>Store</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @category.products.each do |product| %>
      <tr>
        <td><%= image_tag product.image_url(:thumb) %></td>
        <td><%= product.name %></td>
        <td>$<%= product.price %></td>
        <td><%= product.stock_level %></td>
        <td><%= product.description %></td>
        <td><%= product.category.name %></td>
        <td><%= product.store.name %></td>
        <td><%= link_to 'Show', product %></td>
        <% if product.store.user == current_user || user_signed_in? && current_user.has_role?(:admin)%>
        <td><%= link_to 'Edit', edit_product_path(product)%></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <% end %>
     </tr>
    <% end %>
  </tbody>
</table>
  <% else %>
<p>There are no products in this category yet.</p>
<% end %>

<button><%= link_to 'Edit', edit_category_path(@category) if user_signed_in? && current_user.has_role?(:admin)%></button>
<button><%= link_to 'Back', categories_path %></button>

</div>