config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users
  resources :charges
  resources :locations
  resources :stores
  resources :categories
  resources :products
  resources :users
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :store
  mount_uploader :image, ProductImageUploader
  resourcify
  validates :name, :price, :stock_level, :category, :image, presence: true
  validates_uniqueness_of :name
  validates :description, presence: true, length: {in: 20..200}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    filter_params.each do |key, value|
      @products = @products.public_send(key,value) if value.present?
    end
  end


  # GET /products/1
  # GET /products/1.json
  def show
    @store = @product.store
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.store = current_user.store

      respond_to do |format|
        if @product.save
          format.html { redirect_to @product, notice: 'Product was successfully created.' }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    # not_authorized and return unless current_user.can_delete?(@product)
    #
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def not_authorized
      flash[:notice] = "You are not authorized"
      redirect_to products_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :stock_level, :description, :image, :category_id)
    end

    def filter_params
      params.slice(:search_term)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :price %> $
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :stock_level %>
    <%= form.number_field :stock_level, id: :product_stock_level %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :product_image %>
  </div>

  <div class="field">
     <%= form.label :category %>
     <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :name), id: :product_category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container">

<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<button><%= link_to 'Show', @product %></button>
<button><%= link_to 'Back', products_path %></button>
</div>

app/views/products/index.html.erb
<% #hide pic for search %>
<% if !params[:search_term] %>
<div class="home-header">
  <div style="z-index:10; width:100%; height:100%; display:flex; justify-content:center; align-items:center; background-color:rgba(0,0,0,0.4)"><h1 class="feat-txt"><span class="cursive-txt">Live a zero waste life</span><br> with home-made food in<br>packaging that won't <br>cost the earth.</h1></div>
</div>
<% end %>
<% #hide pic for search %>

<div class="container">
<br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Price</th>
      <th>Stock level</th>
      <th>Description</th>
      <th>Category</th>
      <th>Store</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><div class="image-cropper"><%= image_tag product.image_url(:thumb)%></div></td>
        <td><%= product.name %></td>
        <td>$<%= product.price %></td>
        <td><%= product.stock_level %></td>
        <td><%= product.description %></td>
        <td><%= product.category.name %></td>
        <td><%= product.store.name %></td>
        <td><%= link_to 'Show', product %></td>
        <% if product.store.user == current_user || user_signed_in? && current_user.has_role?(:admin)%>
        <td><%= link_to 'Edit', edit_product_path(product)%></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%if user_signed_in? && current_user.store.present?%>
<button><%= link_to 'Add New Product', new_product_path %></button>
<% else %>
<button><%= link_to 'Create a Store to Post a Product', new_store_path %></button>
<% end %>
<br>
<br>
</div>

app/views/products/new.html.erb
<div class="container">

<h1>New Product</h1>

<%= render 'form', product: @product %>

<button><%= link_to 'Back', products_path %></button>

</div>

app/views/products/show.html.erb
<div class="container">

<div class="image-med">
  <%= image_tag @product.image_url(:medium)%>
</div>
<br>
<br>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @product.price %>
</p>

<% if current_user == @store.user %>
<p>
  <strong>Stock level:</strong>
  <%= @product.stock_level %>
</p>
<% end %>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>

<p>
  <strong>Store:</strong>
  <%= @product.store.name %>
</p>

<p>
  <strong>Store Location:</strong>
  <%= @product.store.location.full_address %>
</p>

<button><%= link_to 'Back', products_path %></button><% if current_user && current_user == @store.user %>
  <button><%= link_to 'Edit', edit_product_path(@product) %></button>
<% else %>
<br><br>
<%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    </article>

    <%= hidden_field_tag :product_id, @product.id %>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="<%= @product.name %>"
            data-amount="<%= @product.price * 100 %>"
            data-locale="auto"></script>
  <% end %>
</div>

<% end %>